# Generated by Django 2.1.2 on 2018-12-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
                ('regid', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='', max_length=128)),
                ('status', models.SlugField(choices=[('valid', 'valid'), ('invalid', 'invalid'), ('present', 'present')], default='valid', max_length=8)),
                ('comment', models.CharField(default='Prepared to add', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='AddUsersImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_pid', models.SmallIntegerField(null=True)),
                ('importer', models.CharField(max_length=80)),
                ('importer_id', models.CharField(max_length=16)),
                ('importing', models.SmallIntegerField()),
                ('imported', models.SmallIntegerField(default=0)),
                ('course_id', models.CharField(max_length=80)),
                ('section_id', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=80)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('import_error', models.TextField(null=True)),
            ],
        ),
    ]
