# Generated by Django 2.2.17 on 2021-01-14 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='importjob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='canvas_users.AddUsersImport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addusersimport',
            name='notify_users',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='addusersimport',
            name='role_base',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addusersimport',
            name='role_id',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addusersimport',
            name='section_only',
            field=models.NullBooleanField(),
        ),
    ]
