# Generated by Django 2.2.17 on 2021-01-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addusersimport',
            name='import_pid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
