autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
targetAverageUtilization: 100
affinity:
   podsSpanNodes: true

ingress:
  enabled: true
  tls:
    course-users:
      secretName: course-users.canvas.uw.edu-ingress-cert
      hosts:
        - course-users.canvas.uw.edu
  hosts:
    course-users:
      host: course-users.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

lifecycle:
  enabled: true
  preStop:
    enabled: true
readiness:
  enabled: true

externalService:
  enabled: true
  name: course-users-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.28
  servicePort: 3306
database:
  engine: mysql
  name: course_users_prod
  hostname: course-users-db-service
  secretName: course-users.canvas.uw.edu-sql-secrets

repo: course-users
instance: prod

memcached:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate

certs:
  mounted: false

environmentVariables:
  - name: CLUSTER_CNAME
    value: course-users.canvas.uw.edu
  - name: AUTH
    value: BLTI
  - name: ENV
    value: prod
  - name: SESSION_BACKEND
    value: MEMCACHED
  - name: CANVAS_ENV
    value: PROD
  - name: CANVAS_TIMEOUT
    value: "60"
  - name: SIS_PROVISIONER_ENV
    value: PROD

externalSecrets:
  enabled: true
  secrets:
    - name: course-users.canvas.uw.edu-secrets
      externalKey: course-users/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: sis-provisioner-api-token
          property: sis-provisioner-api-token
    - name: course-users.canvas.uw.edu-shared-secrets
      externalKey: course-users/shared/secrets
      data:
        - name: lti-consumers
          property: lti-consumers
        - name: blti-aes-key
          property: blti-aes-key
        - name: blti-aes-iv
          property: blti-aes-iv
    - name: course-users.canvas.uw.edu-canvas-secrets
      externalKey: canvas/shared/secrets
      data:
        - name: canvas-account-id
          property: canvas-account-id
        - name: continuum-account-id
          property: continuum-account-id
        - name: canvas-api-token
          property: canvas-api-token
    - name: course-users.canvas.uw.edu-sql-secrets
      externalKey: canvas/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: course-users.canvas.uw.edu-secrets
    secretKey: django-secret
  LTIConsumers:
    name: LTI_CONSUMERS
    secretName: course-users.canvas.uw.edu-shared-secrets
    secretKey: lti-consumers
  BLTIAESKey:
    name: BLTI_AES_KEY
    secretName: course-users.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-key
  BLTIAESIV:
    name: BLTI_AES_IV
    secretName: course-users.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-iv
  canvasAPIToken:
    name: CANVAS_OAUTH_BEARER
    secretName: course-users.canvas.uw.edu-canvas-secrets
    secretKey: canvas-api-token
  canvasAccountID:
    name: CANVAS_ACCOUNT_ID
    secretName: course-users.canvas.uw.edu-canvas-secrets
    secretKey: canvas-account-id
  continuumAccountID:
    name: CONTINUUM_CANVAS_ACCOUNT_ID
    secretName: course-users.canvas.uw.edu-canvas-secrets
    secretKey: continuum-account-id
  sisProvisionerAPIToken:
    name: SIS_PROVISIONER_OAUTH_BEARER
    secretName: course-users.canvas.uw.edu-secrets
    secretKey: sis-provisioner-api-token
