ingress:
  enabled: true
  tls:
    course-users:
      secretName: test-course-users.canvas.uw.edu-ingress-cert
      hosts:
        - test-course-users.canvas.uw.edu
  hosts:
    course-users:
      host: test-course-users.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: course-users-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.28
  servicePort: 3306
database:
  engine: mysql
  name: course_users_test_daemon
  hostname: course-users-db-service
  secretName: test-course-users.canvas.uw.edu-sql-secrets
repo: course-users
instance: test
image:
  repository: gcr.io/uwit-mci-axdd/course-users
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
certs:
  mounted: false
daemon:
  enabled: true
  daemons:
    - name: import-users
      replicaCount: 1
      command: ["/scripts/management_daemon.sh"]
      args: ["--delay", "10", "import_users"]
environmentVariables:
  - name: CLUSTER_CNAME
    value: test-course-users.canvas.uw.edu
  - name: AUTH
    value: BLTI
  - name: ENV
    value: test
  - name: SESSION_BACKEND
    value: MEMCACHED
  - name: CANVAS_ENV
    value: EVAL
  - name: CANVAS_TIMEOUT
    value: "60"
  - name: SIS_PROVISIONER_ENV
    value: EVAL
  - name: WEBSERVER
    value: nginx
externalSecrets:
  enabled: true
  secrets:
    - name: test-course-users.canvas.uw.edu-secrets
      externalKey: axdd/kv/data/course-users/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: sis-provisioner-api-token
          property: sis-provisioner-api-token
    - name: test-course-users.canvas.uw.edu-shared-secrets
      externalKey: axdd/kv/data/course-users/shared/secrets
      data:
        - name: lti-consumers
          property: lti-consumers
        - name: blti-aes-key
          property: blti-aes-key
        - name: blti-aes-iv
          property: blti-aes-iv
    - name: test-course-users.canvas.uw.edu-canvas-secrets
      externalKey: axdd/kv/data/canvas/shared/secrets
      data:
        - name: canvas-account-id
          property: canvas-account-id
        - name: continuum-account-id
          property: continuum-account-id
        - name: canvas-api-token
          property: canvas-api-token
    - name: test-course-users.canvas.uw.edu-sql-secrets
      externalKey: axdd/kv/data/canvas/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test-course-users.canvas.uw.edu-secrets
    secretKey: django-secret
  LTIConsumers:
    name: LTI_CONSUMERS
    secretName: test-course-users.canvas.uw.edu-shared-secrets
    secretKey: lti-consumers
  BLTIAESKey:
    name: BLTI_AES_KEY
    secretName: test-course-users.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-key
  BLTIAESIV:
    name: BLTI_AES_IV
    secretName: test-course-users.canvas.uw.edu-shared-secrets
    secretKey: blti-aes-iv
  canvasAPIToken:
    name: CANVAS_OAUTH_BEARER
    secretName: test-course-users.canvas.uw.edu-canvas-secrets
    secretKey: canvas-api-token
  canvasAccountID:
    name: CANVAS_ACCOUNT_ID
    secretName: test-course-users.canvas.uw.edu-canvas-secrets
    secretKey: canvas-account-id
  continuumAccountID:
    name: CONTINUUM_CANVAS_ACCOUNT_ID
    secretName: test-course-users.canvas.uw.edu-canvas-secrets
    secretKey: continuum-account-id
  sisProvisionerAPIToken:
    name: SIS_PROVISIONER_OAUTH_BEARER
    secretName: test-course-users.canvas.uw.edu-secrets
    secretKey: sis-provisioner-api-token
